loss:
  weight_dice: 0.7
  weight_le: 0.2
  weight_mse: 0.1
model:
  feat_dim: 6
  k_neighbors: 32
  n_neighbors: 32
  n_nodes: 11236
  n_surface: 7465
  num_layer: 6
paths:
  checkpoint_dir: train/checkpoints
  samples_dir: data
  shared_dir: output/shared
  splits_dir: train/splits
training:
  batch_size: 8
  lr: 0.001
  max_epochs: 200
  scheduler: ReduceLROnPlateau
  scheduler_patience: 10
  weight_decay: 0.0001
